services:
  postgresql:
    container_name: dev-postgres
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./RootFS/database/postgres/data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: dev-pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@test.org
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - ./RootFS/database/pgadmin/:/var/lib/pgadmin
