services:
  freeradius:
    container_name: freeradius
    build:
      context: ./
      dockerfile: freeradius.Dockerfile
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./RootFS/debug:/var/debug
      - ./RootFS/config/clients.conf:/etc/raddb/clients.conf
      - ./RootFS/config/users:/etc/raddb/users
      - ./RootFS/config/radiusd.conf:/etc/raddb/radiusd.conf
    restart: unless-stopped
    networks:
      - radius-net

networks:
  radius-net:
    driver: bridge
    ipam:
        config:
            - subnet: 192.168.200.0/24
