#version: '3.8'
name: nginx

services:
  nginx:
    image: nginx
    container_name: nginx # 사용할 컨테이너 이름
    environment:
      - TZ=Asia/Seoul
    ports: 
      - 80:80 # 외부 포트 : 내부 포트
      - 443:443
    volumes: # 외부 경로 : 컨테이너 내부 경로
      - ./rootfs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./rootfs/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./rootfs/var/www:/var/www
    restart: always
