version: "3"

services:
  db:
    container_name: dev-mariadb
    build:
      context: ./
      dockerfile: mariadb.Dockerfile
    ports:
      - "3306:3306"
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345*"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./RootFS/database/mysql/data:/var/lib/mysql
